LangString addOrReinstall ${LANG_POLISH} "Dodaj lub zainstaluj ponownie składniki"
LangString alreadyInstalled ${LANG_POLISH} "Już zainstalowano"
LangString alreadyInstalledLong ${LANG_POLISH} "${PRODUCTNAME} ${VERSION} jest już zainstalowana. Wybierz operację i kliknij Dalej."
LangString appRunning ${LANG_POLISH} "{{product_name}} działa! Zamknij ją i spróbuj ponownie."
LangString appRunningOkKill ${LANG_POLISH} "{{product_name}} działa!$\nKliknij OK, aby ją zamknąć."
LangString chooseMaintenanceOption ${LANG_POLISH} "Wybierz operację konserwacyjną."
LangString choowHowToInstall ${LANG_POLISH} "Wybierz sposób instalacji ${PRODUCTNAME}."
LangString createDesktop ${LANG_POLISH} "Utwórz skrót na pulpicie"
LangString dontUninstall ${LANG_POLISH} "Nie odinstalowuj"
LangString dontUninstallDowngrade ${LANG_POLISH} "Nie odinstalowuj (instalacja starszej wersji bez odinstalowania jest zablokowana — do poprzedniej wersji wracaj przez Ustawienia → Aktualizacje)"
LangString failedToKillApp ${LANG_POLISH} "Nie udało się zamknąć {{product_name}}. Zamknij ją i spróbuj ponownie."
LangString installingWebview2 ${LANG_POLISH} "Instalowanie WebView2..."
LangString newerVersionInstalled ${LANG_POLISH} "Zainstalowano już nowszą wersję ${PRODUCTNAME}! Do poprzedniej wersji wracaj przez Ustawienia → Aktualizacje → „Przywróć poprzednią wersję”. Wybierz operację i kliknij Dalej."
LangString older ${LANG_POLISH} "starsza"
LangString olderOrUnknownVersionInstalled ${LANG_POLISH} "W systemie jest zainstalowana wersja ${PRODUCTNAME} ($R4). Aby zachować ją do przywrócenia (Ustawienia → Aktualizacje), wybierz „Nie odinstalowuj”. Wybierz operację i kliknij Dalej."
LangString silentDowngrades ${LANG_POLISH} "Instalacja starszej wersji jest zablokowana — instalator cichy nie może kontynuować; użyj instalatora graficznego.$\n"
LangString unableToUninstall ${LANG_POLISH} "Nie można odinstalować!"
LangString uninstallApp ${LANG_POLISH} "Odinstaluj ${PRODUCTNAME}"
LangString uninstallBeforeInstalling ${LANG_POLISH} "Odinstaluj przed instalacją"
LangString unknown ${LANG_POLISH} "nieznana"
LangString webview2AbortError ${LANG_POLISH} "Nie udało się zainstalować WebView2! Aplikacja bez niego nie działa. Uruchom instalator ponownie."
LangString webview2DownloadError ${LANG_POLISH} "Błąd: pobieranie WebView2 nie powiodło się - $0"
LangString webview2DownloadSuccess ${LANG_POLISH} "Pobrano instalator WebView2"
LangString webview2Downloading ${LANG_POLISH} "Pobieranie instalatora WebView2..."
LangString webview2InstallError ${LANG_POLISH} "Błąd: instalacja WebView2 zakończyła się kodem $1"
LangString webview2InstallSuccess ${LANG_POLISH} "Zainstalowano WebView2"
LangString deleteAppData ${LANG_POLISH} "Usuń także dane Alfy (rozmowy, pamięć, modele, ustawienia)"
